{"uuid": "0a76b9e1-3afa-49ff-8534-e9336c8816fe", "befores": [{"name": "setup_platform", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\Pull from GitHub\\\\util\\\\constants.json'\n", "trace": "  File \"C:\\Users\\DELL-L7480\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL-L7480\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\DELL-L7480\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\DELL-L7480\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\DELL-L7480\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Pull from GitHub\\mcd_test_automation\\conftest.py\", line 163, in setup_platform\n    with open(constants_path) as constant_file:\n         ~~~~^^^^^^^^^^^^^^^^\n"}, "start": 1746444375828, "stop": 1746444375828}], "start": 1746444375828, "stop": 1746444376608}